SEQUENCE: '012_frisbee'
INVALID_ARIAS: []
INVALID_EXOS: []
# USE_EXO_RADTANPRISM: False
USE_EXO_RADTANPRISM: True
EXO_CALIBRATION_ROOT: '/media/rawalk/disk1/rawalk/datasets/ego_exo/main/frisbee_calibration/exo'

BBOX:
  MIN_VERTICES: 40

  EGO:
    MIN_AREA_RATIO: 0.001
    CLOSE_BBOX_DISTANCE: 3.0
    CLOSE_BBOX_MIN_AREA_RATIO: 0.01
    MAX_ASPECT_RATIO: 4
    MIN_ASPECT_RATIO: 0.4

  EXO:
    MIN_AREA_RATIO: 0.0005
    MAX_ASPECT_RATIO: 5
    MIN_ASPECT_RATIO: 0.5

POSE2D:
  DEBUG: False
  # DEBUG: True

  # USE_BBOX_DETECTOR: False
  USE_BBOX_DETECTOR: True
  DETECTOR_CONFIG_FILE: '/home/rawalk/Desktop/ego/mmpose/demo/mmdetection_cfg/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco.py'
  DETECTOR_CHECKPOINT: 'https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco/faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco_20210524_124528-26c63de6.pth'
  DETECTOR_MIN_IOU: 0.1

  RGB_CONFIG_FILE: '/home/rawalk/Desktop/ego/mmpose/configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/hrnet_w48_coco_wholebody_384x288_dark_plus.py'
  RGB_CHECKPOINT: 'https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth'
  
  # RGB_CONFIG_FILE: '/home/rawalk/Desktop/ego/mmpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/ochuman/hrnet_w48_ochuman_384x288.py'
  # RGB_CHECKPOINT: 'https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_384x288-314c8528_20200708.pth'

  RGB_THRES: 0.2
  RGB_VIS_THRES: 0.2
  
  GRAY_CONFIG_FILE: '/home/rawalk/Desktop/ego/mmpose/configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody-grayscale/hrnet_w48_coco_wholebody_384x288_dark_plus.py'
  GRAY_CHECKPOINT: 'https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth'
  GRAY_THRES: 0.5
  GRAY_VIS_THRES: 0.5

  MIN_VIS_KEYPOINTS: 5
  # OVERLAP_OKS_THRES: 0.8 ## very important, default
  # OVERLAP_OKS_THRES: 0.7 ## very important, stricter threshold
  OVERLAP_OKS_THRES: 0.5 ## very important, stricter threshold
  # OVERLAP_OKS_THRES: 0.4 ## very important, stricter threshold
  # OVERLAP_OKS_THRES: 0.3 ## very important, stricter threshold

  BBOX_THRES: 0.5

  VIS:
    RADIUS:
      EXO_RGB: 6
      EGO_RGB: 3
      EGO_LEFT: 2
      EGO_RIGHT: 2
    THICKNESS:
      EXO_RGB: 6
      EGO_RGB: 3
      EGO_LEFT: 2
      EGO_RIGHT: 2

POSE3D:
  KEYPOINTS_THRES: 0.5
  BBOX_AREA_THRES: 0.003
  NUM_ITERS: 500
  REPROJECTION_ERROR_EPSILON: 0.01
  MIN_VIEWS: 4 ## min views for triangulation
  MIN_INLIER_VIEWS: 4 ## min views for triangulation
  SECONDARY_MIN_VIEWS: 3 ## min views for triangulation
  INCLUDE_CONFIDENCE: False ## include confidence in triangulation  

REFINE_POSE3D:
  DEBUG: True
  STD_THRES: 5 ##+- std deviation allowed for inliers
  WINDOW_LENGTH: 10
  IQR_THRES: 8
  MOTION_THRES: 300 ## in pixels 4k

INIT_SMPL:
  # VIS: True
    VIS: False

BLENDER:
  SCENE_FILE: 'frisbee/frisbee.blend'
  COLORS: 'blue###green###red###yellow###purple###orange'